### ISSUE TITLE
Hi. i have a question about apply shortcut in vsCode

### ISSUE THREAD

**Issue by DUHEON** [compulim/vscode-closetag#14]
First. Thank you for your vscode-closetag
I really needed this extension pg
anyway, 
I want to change the shortcut this pg in vs-code
so I tried to change shortcut what you says 

My setting place already chagned font, .. whatever
and added it this code
{
 ... << this is my setting code
 "key" : "/",
 "command" : "closeTag.closeHTMLTag",
 "when" : "editorTextFocus"
}

When I add that 
I think when I press "/" button execute like when I press button "alt + . " 

but it didn't work..
how can I work that like my thinking
plz reply my question 
Have a good day

**Comment by compulim** [comment]
I think it is VSCode prevented key binding without modifier.
