### ISSUE TITLE
Running the contributed command:'closeTag.closeHTMLTagInPlace' failed.

### ISSUE THREAD

**Issue by dbaines** [compulim/vscode-closetag#15]
Issue Type: <b>Bug</b>

Pressing the keyboard shortcut `command + alt + .` shows this error:

`Running the contributed command:'closeTag.closeHTMLTagInPlace' failed.`

Running the command from command pallette works fine.
Only started after updating vs code to today's new version.

Have tried uninstalling and reinstalling extension, does not fix.

Extension version: 1.1.0
VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:30:30.113Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by lostkeys** [comment]
+1

**Comment by yomotsu** [comment]
same here
![2](https://user-images.githubusercontent.com/212837/41193798-9ef5848a-6c4c-11e8-88e1-33e463796750.gif)

**Comment by yomotsu** [comment]
same here
![2](https://user-images.githubusercontent.com/212837/41193818-1598fe14-6c4d-11e8-9723-babb5ef7f1d8.gif)

**Comment by compulim** [comment]
Working on it, should be out within an hour.

**Comment by compulim** [comment]
Fixed in [1.1.1](https://github.com/compulim/vscode-closetag/releases/tag/v1.1.1).
